<link rel="stylesheet" href="<?php echo $assetsurl; ?>css/bootstrap.min.css" />
<link rel="stylesheet" href="<?php echo $assetsurl; ?>css/all.min.css" />
<link rel="stylesheet" href="<?php echo $assetsurl; ?>css/toastr.min.css" />
<link rel="stylesheet" href="<?php echo $assetsurl; ?>css/select2.min.css" />
<link rel="stylesheet" href="<?php echo $assetsurl; ?>highlightjs/styles/zenburn.css" />
<link rel="stylesheet" href="<?php echo $assetsurl; ?>css/main.css" />