<head>
    <title>Rusty's Tools - <?php echo $toolname; ?></title>
    <meta encoding="UTF-8"/>
    <meta title="<?php echo $toolname; ?> - Rusty's Tools" description="<?php echo $toolDescShort; ?>"/>
    <?php include $templatedir."head/cssfiles.phtml"; ?>
    <script>
        var baseurl = "<?php echo $baseurl; ?>";
        var toolurl = "<?php echo $baseurl."tools/".$toolshort."/"; ?>";
    </script>
</head>