<script src="<?php echo $assetsurl; ?>js/jquery-3.3.1.min.js"></script>
<script src="<?php echo $assetsurl; ?>js/popper.min.js"></script>
<script src="<?php echo $assetsurl; ?>js/bootstrap.min.js"></script>
<script src="<?php echo $assetsurl; ?>js/toastr.min.js"></script>
<script src="<?php echo $assetsurl; ?>fontawesome/js/all.min.js"></script>
<script src="<?php echo $assetsurl; ?>js/select2.min.js"></script>
<script src="<?php echo $assetsurl; ?>highlightjs/highlight.js"></script>
<script src="<?php echo $assetsurl; ?>js/main.js"></script>