<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="margin-bottom:15px;">
    <a class="navbar-brand" href="<?php echo $baseurl; ?>">Rusty's Tools</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <?php echo $additionalNavItems; ?>
			<li class='nav-item'><a class='nav-link' href='https://discord.gg/DrKNGQn'><i class="fab fa-lg fa-discord"></i>&nbsp;Support on Discord</a></li>
			<li class='nav-item'><a class='nav-link' href='https://rusty.info/'><i class="fa fa-lg fa-comments"></i>&nbsp;Support on Forum</a></li>
        </ul>
        <ul class="navbar-nav justify-content-end text-light">
            <?php echo $additionalNavItemsRight; ?>
        </ul>
    </div>
</nav>