<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="margin-bottom:15px;">
    <a class="navbar-brand" href="<?php echo $baseurl; ?>">Rusty's Tools</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <?php echo $additionalNavItems; ?>
        </ul>
        <ul class="navbar-nav nav justify-content-end">
            <?php echo $additionalNavItemsRight; ?>
        </ul>
    </div>
</nav>